name: cab_booking_manager
description: "Cab Booking Management System"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.5+1

  # Date & Time Formatting
  intl: ^0.20.3

  # Local Database
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.14.4

  # Local Settings (will be removed later if no longer required)
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/cab.png"
  min_sdk_android: 21
  remove_alpha_ios: true